dist: xenial
# Use the latest Travis images since they are more up to date than the stable release.
group: edge
services:
  - docker
matrix:
  include:
    # Run JS tests
    - language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      cache: yarn
      before_install:
        # Try to keep version in sync with `package.json`
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn install --frozen-lockfile
      script:
        - yarn test:coverage
        - yarn codecov

    # Run Heroku build & release related code
    - language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      install:
        - yarn install --prod --frozen-lockfile
      script:
        - yarn build

    # Run basic linters
    - language: minimal
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      python: '3.7'
      cache:
        - pip
        - yarn
      install:
        - yarn install
        - pip install -r requirements/common.txt
        - pip install -r requirements/dev.txt
        - pip install -r requirements/docs.txt
      script:
        # `yarn build` is tested as part of the Selenium job.
        - yarn lint
        # `yarn lint` only checks the formatting of JS/JSX, this will also check CSS/HTML/JSON/Markdown/YAML.
        - yarn format:check
        - ./runchecks.sh

    # Run Python tests outside of the Docker containers
    - language: python
      python: '3.7'
      cache: pip
      install:
        # Initialize services required to run tests
        - docker-compose up --detach mysql redis rabbitmq
        - pip install -r requirements/common.txt -r requirements/dev.txt
      script:
        - ./manage.py check
        # Exercising running tests outside of Docker
        - DATABASE_URL=mysql://root@127.0.0.1:3306/treeherder pytest tests/ --ignore=tests/selenium --ignore=tests/extract
        # This is to deal with running the containers with --detached
        - docker-compose down

    # Run Python tests inside of the Docker containers
    - language: minimal
      install:
        - docker-compose build
        - pip install codecov --user
      script:
        - docker-compose run backend bash -c "pytest --cov --cov-report=xml tests/ --runslow --ignore=tests/selenium"
        - codecov -f coverage.xml

    # Run Python Selenium tests
    - env: python-tests-selenium
      language: node_js
      # The Node version here must be kept in sync with that in `package.json`.
      node_js: '12.13.0'
      cache:
        directories:
          - node_modules
      before_install:
        - docker-compose build
      install:
        - yarn install
        - pip install codecov --user
      before_script:
        # Run in `before_script` to prevent the Selenium tests from running if the UI build fails.
        - yarn build
      script:
        # Several security features in settings.py (eg setting HSTS headers) are conditional on
        # 'https://' being in the site URL. In addition, we override the test environment's debug
        # value so the tests pass. The real environment variable will be checked during deployment.
        - docker-compose run backend bash -c "SITE_URL=https://treeherder.dev TREEHERDER_DEBUG=False
          ./manage.py check --deploy --fail-level WARNING"
        # XXX: We have the Gecko driver inside of the Docker instance, thus, needing Selenium tests
        # running inside the Docker container
        - docker-compose run backend bash -c "pytest --cov --cov-report=xml tests/selenium/"
        - codecov -f coverage.xml

notifications:
  email:
    on_success: never
    on_failure: always
